### ISSUE TITLE
[Feature] Turn Chat Messages [On/Off]

### ISSUE THREAD

**Issue by Peinful** [VanillaPlusPlus/SupplyDropPlus#2]
**Is your feature request related to a problem, or flaw? Please describe.**
Allowing server owners to turn the message on and off for the supply drops would be extremely useful.

**Describe the solution you'd like**
Messages not to be printed of locations inside of the server's chat.

**Comment by GravityWolfNotAmused** [comment]
https://github.com/VanillaPlusPlus/SupplyDropPlus/commit/41f7944f5eabd82366aae3f02bcf3ca5ee485fd0

**Comment by GravityWolfNotAmused** [comment]
Thank you again, Peinful.
